---
#
# Ansible managed
#
repository:
  description: Install and configure ara on your system.
  homepage: https://robertdebock.nl/
  topics: ansiblerecordsansible, ara, arareportsansible, cloud, development, monitoring, reporting, hacktoberfest
