---

- name: test if ara_configuration_file is set correctly
  assert:
    that:
      - ara_configuration_file is defined
    quiet: yes

- name: test if ara_user is set correctly
  assert:
    that:
      - ara_user is defined
    quiet: yes

- name: test if ara_configuration is set correctly
  assert:
    that:
      - ara_configuration is iterable
    quiet: yes
  when:
    - ara_configuration is defined

- name: test if item in ara_configuration is set correctly
  assert:
    that:
      - item.option is defined
      - item.value is defined
    quiet: yes
  loop: "{{ ara_configuration }}"
  loop_control:
    label: "{{ item.option }}"
  when:
    - ara_configuration is defined
