---
# handlers file for ara

- name: restart ara
  service:
    name: ara
    state: restarted
  become: yes
  when:
    - not ansible_check_mode | bool

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  become: yes
  notify:
    - restart ara
